name = "Startup"
uuid = "047500d8-b0e7-490c-83b9-9904e4003dce"
authors = ["Dheepak Krishnamurthy"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
